### ISSUE TITLE
How can I add the application files to GitHub ?

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/javascript-todo-list-tutorial#16]
How can I add the application files to GitHub ? I've never been able to add a folder, I'd like to know how to do it.

**Comment by yawmanford** [comment]
You have to be familiar with the command line/terminal and git to do that. This would help: https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners

**Comment by miguelmartins17** [comment]
Thanks for your help. I'll take a look at the tutorial. @yawmanford

**Comment by nelsonic** [comment]
Closing as no longer an issue. ✅
