### ISSUE TITLE
NPM Install Error

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/javascript-todo-list-tutorial#21]
Yesterday when I tried to run this command nothing happened but today running the command showed me a series of errors.
I've been researching what these mistakes would be.

![Screen Shot 2020-01-24 at 19 08 04](https://user-images.githubusercontent.com/27420533/73096818-a0853380-3edd-11ea-949d-a7fbf1677a18.png)

**Comment by miguelmartins17** [comment]
I've been reading the errors one by one and one of them asks me to install the node-gyp-build.

https://www.npmjs.com/package/node-gyp-build

**Comment by miguelmartins17** [comment]
Even after installing node-gyp-build the same error still appears.
What about the bufferutil package?

![Screen Shot 2020-01-24 at 19 21 50](https://user-images.githubusercontent.com/27420533/73097394-fd351e00-3ede-11ea-9ebf-4ab747608695.png)

**Comment by miguelmartins17** [comment]
Here's what I researched about the bufferutil package.

![Screen Shot 2020-01-24 at 19 28 58](https://user-images.githubusercontent.com/27420533/73097793-e7742880-3edf-11ea-8f18-6863a4b18526.png)

**Comment by nelsonic** [comment]
@miguelmartins17 what was the _exact_ `npm` command you attempted to run that resulted in the error above? And why did it take you so long to open this issue? The _moment_ you get _stuck_ you should open an issue. Otherwise we are _blind_ to your struggles ... 😞

**Comment by miguelmartins17** [comment]
That's what I explained above. Yesterday when I ran the command nothing happened but today when I ran it those errors appeared. 😕 
It was this command that generated all those errors.

![Screen Shot 2020-01-25 at 09 09 51](https://user-images.githubusercontent.com/27420533/73118909-82a5e600-3f52-11ea-8858-d60405859319.png)

**Comment by nelsonic** [comment]
Ok, so you are attempting to **`npm install`** the dependencies for this project. 🤔
Did the **`git clone`** work in the previous step?
i.e. do you have a directory called **`javascript-todo-list-tutorial`** ?

**Comment by miguelmartins17** [comment]
Yes, the git clone worked.
The terminal's path changed to the board of directors right when I ran the **_git clone_** command.
Only in the next step and yesterday this error occurred because the day before I had run the **_npm install_** command and had not given error.
