### ISSUE TITLE
Update devDependencies

### ISSUE THREAD

**Issue by nelsonic** [dwyl/javascript-todo-list-tutorial#25]
https://david-dm.org/dwyl/javascript-todo-list-tutorial?type=dev
![image](https://user-images.githubusercontent.com/194400/80358824-e521c180-8874-11ea-8913-a81fa033affa.png)

# Todo
+ [x] update version of `tape` `^4.13.0` -> `5.0.0`
+ [x] re-run tests to confirm everything still works e.g: https://github.com/dwyl/learn-tape/pull/45
(_or just push your branch to GitHub and let Travis-CI do the checking_)
+ [x] Create PR.

Happy for _anyone_ `else` to do this. 🌻

**Comment by cristianofromagio** [comment]
I can PR this, might need to wait for #27 to be merged tho

**Comment by nelsonic** [comment]
@cristianofromagio #27 merged. (_thanks!_)

**Comment by nelsonic** [comment]
All up-to-date. ✅ 
Thanks again @cristianofromagio
