### ISSUE TITLE
Update test -> TypeError: app.update is not a function

### ISSUE THREAD

**Issue by ArthurFAmaral95** [dwyl/javascript-todo-list-tutorial#64]
I've tried running the first test for the update function, but I keep getting the same error message. TypeError: app.update is not a function.

![Screen Shot 2023-03-25 at 18 08 41](https://user-images.githubusercontent.com/105131330/227742069-0849e6a1-5edd-4a48-86c8-7b05a407daeb.png)

**Comment by ArthurFAmaral95** [comment]
Found what I was doing wrong. Missing export function.

**Comment by nelsonic** [comment]
Hi @ArthurFAmaral95 👋
Glad you figured it out. 👌
How did you discover this tutorial? 💭

**Comment by ArthurFAmaral95** [comment]
I was looking for repositories with practical exercises to practice HTML, CSS and JS and found this one: https://github.com/practical-tutorials/project-based-learning

**Comment by nelsonic** [comment]
Sweet. Thanks for sharing. 👌
