### ISSUE TITLE
Cloning repo is more complete than the tutorial indicates

### ISSUE THREAD

**Issue by JoeFry15** [dwyl/javascript-todo-list-tutorial#67]
Hi all,

Just started this project and I've cloned the repo. Lots of files are already created and written even though the tutorial mentions creating them anew.

e.g. the "test/todo-app.test.js" file already exists with 80 odd tests already written but the tutorial guides one through creating this file and explaining it should be empty.

Am I missing something? Do I need to go to a specific commit?

Thanks,

Joe

**Comment by nelsonic** [comment]
Clarified in `README.md` ✅
