### ISSUE TITLE
Biny!

### ISSUE THREAD

**Issue by ndrean** [dwyl/javascript-todo-list-tutorial#71]
Not sure if this is the right place... Self advert and the  "Yet Another FrontEndFramework" syndrom in action... I made a tiny package as a helper to write super easily (in my opinion) reactive UI with a tiny 1.4kB package. The todoMVC code is displayed and the JS-framework test is as well.

What is the point? I needed something really small to add to a static site and can up with this. It is pretty fast and very lightweight but of course not a revolution. 

Source: <https://github.com/ndrean/binyJS>

`binyjs` on `npm`

Terse explanation: <https://dev.to/ndrean/yet-another-micro-package-for-reactive-ui-574k>

**Comment by nelsonic** [comment]
@ndrean yeah, this is probably not the place for showcasing a JS framework. 💭 
The whole idea of this tutorial is help people build the `TodoMVC` _without_ a framework. 🙅 
***Or*** to build it themselves from first principals: https://github.com/dwyl/javascript-todo-list-tutorial/blob/main/elmish.md

Looks good though. 👌
